variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  
cache:
  paths:
    - .cache/pip
    - venv/
    
stages:
  - build
  - upload

default:
  image: firexstuff/firex-alpine-build:3.12.1
  before_script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    
build:
  stage: build
  script:
    - pip install wheel
    - pip install setuptools
    - python firexbuilder/build.py build
  artifacts:
    paths:
      - dist/

upload-pkg:
  stage: upload
  script:
    - pip install keyrings.alt
    - firex-build upload_pip
  only:
    - tags
